version: '3.4'

services:
  employeeadministration.api:
    image: ${DOCKER_REGISTRY-}employeeadministrationapi
    container_name: employeeadministration.api
    build:
      context: .
      dockerfile: EmployeeAdministration.API/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    depends_on:
        - employeeadministration.database
  
  employeeadministration.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: employeeadministration.database
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Data@entry12base
    volumes:
        - ./.containers/employeeadministration-db/data:/var/opt/mssql/data
    ports:
        - "1433:1433"
    depends_on:
        - employeeadministration.cache

  employeeadministration.cache:
    image: redis:latest
    container_name: employeeadministration.cache
    restart: always
    ports:
        - "6379:6379"